# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8cb77af43a7504e6f66f71eb8d515769b1bb56d16557242fd82b16002fb0f16047274cdca4664e021aacf3380f4acc8580771d37681b6c791e007a7ac68aef34
  
  recaptcha_site_key: 6LdXHkgUAAAAAD7Np1pRKTNKlHEi2t_fn8Ue6bKo
  recaptcha_secret_key: 6LdXHkgUAAAAACvugCXYOs16_w9JJ8IMddz7PsRm

test:
  secret_key_base: a0c60f1e29c87b4fd14684c625ede982b231b5e46c230b95ef93075dcc6554a42f2df65fc3ca39e3311bff144aedbe405f13d047b4a41ef23e7ccee4f8c3db24

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 8cb77af43a7504e6f66f71eb8d515769b1bb56d16557242fd82b16002fb0f16047274cdca4664e021aacf3380f4acc8580771d37681b6c791e007a7ac68aef34
  recaptcha_site_key: 6LdXHkgUAAAAAD7Np1pRKTNKlHEi2t_fn8Ue6bKo
  recaptcha_secret_key: 6LdXHkgUAAAAACvugCXYOs16_w9JJ8IMddz7PsRm